config/routes.rb
Fence::Application.routes.draw do

  resources :events

  match "/images/uploads/*path" => "gridfs#serve"

  root :to => "homepage#index"
  
  get 'beta' => "beta#info"
  get 'events?sort=upcoming' => 'events#index', :as => 'upcoming_events'
  
  devise_for :users, :skip => [:sessions] do
    get 'login' => 'devise/sessions#new', :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    get 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, :all
    
    unless user.nil?
      can :create, Event
      can :edit, Event, :creator => user
      
      if user.admin?
        can :manage, Event
      end
    end
  end

end

app/models/category.rb
class Category
  include Mongoid::Document

  key :name

  field :name, :type => String
  field :kind, :type => String
  
  index :name
  
  references_many :events, :stored_as => :array, :inverse_of => :categories
  
  scope :noun, where(:kind => 'noun').ascending(:name)
  scope :adjective, where(:kind => 'adjective').ascending(:name)

end

app/models/event.rb
class Event
  include Mongoid::Document

  field :name, :type => String
  field :description, :type => String
  field :start, :type => Time
  field :finish, :type => Time
  field :til_whenever, :type => Boolean
  field :cost
  field :free, :type => Boolean
  
  field :featured, :type => Boolean
  field :page_rank, :type => Integer, :default => 0
  
  before_validation :blank_out_finish, :if => :til_whenever?
  before_validation :blank_out_cost, :if => :free?
  
  references_many :categories, :stored_as => :array, :inverse_of => :events
  
  belongs_to_related :creator, :class_name => "User"
  
  # FIXME: replace with mongoid HABTM support
  # has_one_related :location
  field :location, :type => String
  
  mount_uploader :image, ImageUploader
  validate :image_upload
  
  validate :start_before_finish
  validates_presence_of :start, :name, :description, :location
  validates_presence_of :finish, :unless => :til_whenever
  validates_uniqueness_of :name

  scope :happening_now, where(:start.lt => Time.now, :finish.gt => Time.now)
  scope :featured, where(:featured => true).descending(:page_rank)
  scope :upcoming, where(:start.gt => Time.now)
  
  def to_param
    self.id
  end
  
  def duration
    finish ? finish - start : 0
  end
  
  private
  def start_before_finish
    errors.add(:finish, I18n.t('events.validations.finish_after_start')) if finish && start && finish <= start
  end
  
  def image_upload
    errors.add(:image, I18n.t('events.validations.image_file_type')) if image_integrity_error    
  end
  
  def blank_out_finish
    self.finish = nil
  end
  
  def blank_out_cost
    self.cost = nil
  end
end

app/models/location.rb
class Location
  include Mongoid::Document
  
  field :name, :type => String
  field :address, :type => String
  field :description, :type => String

  # Until HABTM support comes to Mongoid
  # belongs_to_related :event
end

app/models/user.rb
class User
  include Mongoid::Document

  devise :omniauthable, :trackable
         
  has_many_related :events, :foreign_key => :creator_id
  
  field :admin, :type => Boolean, :default => false
  field :email, :type => String

 def self.find_for_pubcookie_oauth(access_token, signed_in_resource=nil)
  data = access_token['extra']['user_hash']
  if user = User.find_by_email(data["name"])
    user
  else
    User.create!(:email => data["name"]) 
  end
end 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout 'application'
  
  rescue_from CanCan::AccessDenied do |exception|
    flash[:notice] = exception.message
    if user_signed_in?
      redirect_to(root_path)
    else
      authenticate_user!
    end
  end
end

app/controllers/beta_controller.rb
class BetaController < ApplicationController
  
  def info; end
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  respond_to :html

  def index
    @events = Event.all
    
    if params[:category_ids]
      @events = @events.any_in(:category_ids => params[:category_ids])
    end
    
    if params[:query]
      @events = @events.any_of({:name => /#{params[:query]}/i},
                        {:description => /#{params[:query]}/i})
    end
    
    if params[:sort] == "upcoming"
      @events = @events.upcoming
    end

    respond_with(@events)
  end

  def new
    authorize! :create, Event, :message => I18n.t('events.create.authorize_message')
    
    @categories = Category.find(:all)
    @event = Event.new
    respond_with(@event)
  end
  
  def create
    authorize! :create, Event, :message => I18n.t('events.create.authorize_message')
    
    @categories = Category.find(:all)
    @event = current_user.events.build(params[:event])
    
    if @event.save
      flash[:notice] = I18n.t('events.create.successful')
    else
      flash[:alert] = @event.errors.full_messages
    end
    
    respond_with(@event)
  end
  
  def update
    @event = Event.find(params[:id])
    
    authorize! :edit, @event, :message => I18n.t('events.edit.authorize_message')
    
    if @event.update_attributes(params[:event])
      flash[:notice] = I18n.t('events.edit.successful')
    else
      # TODO this should be replaced with formtastic methods but I need to Cucumber it
      flash[:alert] = @event.errors.full_messages
    end
    
    respond_with(@event)
  end
  
  def edit
    @event = Event.find(params[:id])
    authorize! :edit, @event, :message => I18n.t('events.edit.authorize_message')
    respond_with(@event)
  end
  
  def show
    @event = Event.find(params[:id])
    respond_with(@event)
  end

end

app/controllers/gridfs_controller.rb
require 'mongo'
        
class GridfsController < ActionController::Metal
  def serve
    gridfs_path = env["PATH_INFO"].gsub("/images/", "")
    begin
      gridfs_file = Mongo::GridFileSystem.new(Mongoid.database).open(gridfs_path, 'r')
      self.response_body = gridfs_file.read
      self.content_type = gridfs_file.content_type
    rescue
      self.status = :file_not_found
      self.content_type = 'text/plain'
      self.response_body = ''
    end
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  respond_to :html

  def index
    @featured = Event.featured
    respond_with(@featured)
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def pubcookie    
    @user = User.find_for_pubcookie_oauth(env["omniauth.auth"], current_user)

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Pubcookie"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.pubcookie_data"] = env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
  
  def short_description(event)
    categories = event.categories
    
    nouns = categories.noun.map(&:name)
    nouns = ["event"] if nouns.empty?
    
    adjectives = categories.adjective.map(&:name)
    
    first_word = adjectives.empty? ? nouns.first : adjectives.first
    
    adjective_phrase = category_links(adjectives, :class => 'adjective').join(", ")
    noun_phrase = category_links(nouns, :class => 'noun').join("/")
  
    phrase = "#{indefinite_article_for(first_word)} #{adjective_phrase} #{noun_phrase}"
  
    phrase.squish!
    phrase.capitalize!
  
    content_tag :span, phrase.html_safe, :class => "short-description"
  end
  
  private
  
  def category_links(categories, options={})
    categories.map do |category|
      content_tag :span, category, :class => ['category'] + [options[:class]].flatten.compact
    end
  end
    
  def indefinite_article_for(word, consonant = 'a', vowel = 'an')
    result = word.to_s.dup
    result.match(/^\W*([aeiou])/i) ? vowel : consonant
  end
  
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/views/beta/info.html.haml
%h1 Hey, early adopter!
%h3 The Fence is beta software

%br/

%p Please excuse our mess. The Fence isn't quite done yet, and you're getting a sneak peak at it before it officially launches. We would love your help to make it the go-to place for campus events, so please let us know how we can improve.

%br/

%p If you find a problem with The Fence, or have an idea for how we can make it better, let us know in the form below!

%br/

%script{:type=>"text/javascript", :charset=>"utf-8"}
  var is_ssl = ("https:" == document.location.protocol);
  var asset_host = is_ssl ? "https://s3.amazonaws.com/getsatisfaction.com/" : "http://s3.amazonaws.com/getsatisfaction.com/";
  document.write(unescape("%3Cscript src='" + asset_host + "javascripts/feedback-v2.js' type='text/javascript'%3E%3C/script%3E"));

%script{:type=>"text/javascript", :charset=>"utf-8"}
  var feedback_widget_options = {};

  feedback_widget_options.display = "inline";  
  feedback_widget_options.company = "fence";
  feedback_widget_options.placement = "left";
  feedback_widget_options.color = "#222";
  feedback_widget_options.style = "idea";
  feedback_widget_options.popular_topics = "idea";
  
  var feedback_widget = new GSFN.feedback_widget(feedback_widget_options);

app/views/events/_event.html.haml
%li.search-result
  = link_to image_tag(event.image.search.url), event_path(event)
  .description
    %h3= link_to event.name, event_path(event)
    %time= event.start
    at
    = link_to event.location, "#TODO", :class=>"location"
    %details= h truncate(event.description, :length => 250)
    = link_to "Read More", event, :class=>"read-more"

app/views/events/_form.html.haml
= semantic_form_for @event, :html => {:multipart => true} do |f|
  = f.semantic_errors
  = f.inputs do
    = f.input :name, :hint => "Choose something distinctive. This is how people will find your event."
    - if can? :manage, @event
      .underneath-input
        = f.input :featured, :as => :boolean, :label => "Featured"
      = f.input :page_rank, :label => "Page Rank", :hint => "Lower numbers are lower on the page.", :input_html => {:type => 'number', :step => '1'}
    = f.input :categories, :as => :check_boxes, :label => "Categories", :wrapper_html => {:class => "category-select"}, :collection => Category.all
    = f.input :description, :hint => "Tell us what to expect, what to bring, and where to go for more information.", :as => :text
    = f.input :cost, :hint => "e.g. $5, a dozen donuts, 1 CulinArt meal. Be sure to mention if it's free."
    .underneath-input
      %span.or or
      = f.input :free?, :as => :boolean, :label => "Free"
    = f.input :location, :label => "Where?", :hint => "e.g. Wean 7500, The Fence, 1000 Morewood Ave."
    = f.inputs :name => "Time" do
      = f.input :start, :label => "From", :input_html => {:class => "datetime"}
      = f.input :finish, :label => "To", :input_html => {:class => "datetime"}
      .underneath-input
        %span.or or
        = f.input :til_whenever?, :as => :boolean, :label => "'Til Whenever"
    = f.input :image, :label => "Poster", :hint => "This will show up in the events search page"
    .underneath-input
      %h4 Current Image
      = image_tag @event.image.medium.url
  = f.buttons

app/views/events/edit.html.haml
%h1 Edit your event

= render 'form'

app/views/events/index.html.haml
#events-list
  %h1 Listing Events
  
  %ul
    = render :partial => 'event', :collection => @events

app/views/events/new.html.haml
%h1 Create a new event

= render 'form'

app/views/events/show.html.haml
.vevent
  %h1.summary=  @event.name
  %aside
    %a.attach{:href => @event.image.url}= image_tag(@event.image.medium.url)
    %ul
      %li= link_to 'Edit', edit_event_path(@event) if can? :edit, @event
  .categories= short_description(@event)
  %p.description= preserve @event.description
  %dl.info
    %dt Start Time
    %dd.dtstart{:title => @event.start.to_formatted_s(:iso8601)}= @event.start.to_formatted_s(:fence_standard)
    %dt End Time
    - if @event.finish
      %dd.dtend{:title => @event.finish.to_formatted_s(:iso8601)}= @event.finish.to_formatted_s(:fence_standard)
    - else
      %dd Til' Whenever
    - if !@event.cost.blank? || @event.free?
      %dt Cost
      - if @event.free?
        %dd Free
      - else
        %dd= @event.cost
    %dt Location
    %dd.location
      = @event.location
      / %div= %{<iframe width="350" height="200" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/?ie=UTF8&amp;ll=37.0625,-95.677068&amp;spn=43.25835,72.509766&amp;z=4&amp;output=embed"></iframe><br /><small><a href="http://maps.google.com/?ie=UTF8&amp;ll=37.0625,-95.677068&amp;spn=43.25835,72.509766&amp;z=4&amp;source=embed" style="color:#0000FF;text-align:left">View Larger Map</a></small>}.html_safe
      %div= %{<div class="mapviewer"><iframe id="map" Name="mapFrame" scrolling="no" frameborder="0" src="http://www.bing.com/maps/embed/?lvl=16&amp;cp=40.444627075866606~-79.94295779587998&amp;sty=r&amp;draggable=true&amp;v=2&amp;where1=5000+Forbes+Ave%2C+Pittsburgh%2C+PA+15213&amp;pp=40.44462707586659~-79.9429792535521&amp;emid=1616a213-1c50-6dd1-3442-f109680bd25c&amp;w=350&amp;h=280"></iframe></div>}.html_safe

app/views/homepage/index.html.haml
= content_for :above do
  #scream
    = link_to 'Plan Your Escape', events_path, :id => 'escape-button'
    %h2#tagline Leave Your Room, get on The Fence
    %p
      The Fence is the event guide for 
      %a{:href=>"http://www.cmu.edu/"} Carnegie Mellon University
      in Pittsburgh, PA.

= content_for :subnav do
  %ul#quick-links
    %li.upcoming-events
      = link_to "View upcoming events", upcoming_events_path, :class => "quick-link"
    %li.tartan-faves
      = link_to "See Tartan picks", beta_path, :class => "quick-link"
    %li.night-out
      = link_to "Plan a night out", beta_path, :class => "quick-link"
        
  = form_tag events_path, :method => :get, :class => "mood-select" do
    %h4.section-header Find an event to suit your mood
    %dl
      %dt Nouns
      %dd
        %ul
          - Category.noun.each do |category|
            %li
              %label<
                = check_box_tag "category_ids[]", category.id, false
                = category.name
      %dt Adjectives
      %dd
        %ul
          - Category.adjective.each do |category|
            %li
              %label<
                = check_box_tag "category_ids[]", category.id, false
                = category.name
    = submit_tag "Find events", :class => "find"

- if(event = @featured.shift)
  .article.featured
    = link_to image_tag(event.image.frontpage.url), event_path(event)
    .description
      %h3= link_to event.name, event_path(event)
      %time= event.start
      = link_to event.location, "#TODO", :class=>"location"
      %details= h truncate(event.description, :length => 200)
      = link_to "Read More", event, :class=>"read-more"
      
%ul.list
  %h3 More Events
  - @featured.each do |event|
    %li
      %h4= link_to event.name, event_path(event)
      .description
        %time= event.start
        %details
          = truncate(event.description, :length => 150)
          = link_to "Read More", event
          
  

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Fence
    = stylesheet_link_tag "reset", "application"
    = javascript_include_tag "right", "form", "beta", "right-calendar"
    = csrf_meta_tag
  %body
    #container
    
      %span#login-links
        - if current_user
          Welcome, #{current_user.email} | #{link_to "Log Out", destroy_user_session_path}
        - else
          #{link_to "Log in", new_user_session_path} | #{link_to "Sign Up", new_user_registration_path}
    
      #header
        = link_to image_tag("logo.png", :alt => "The Fence (beta)", :width => 397, :height => 70), root_path, :id => 'logo'
        #presented-by{:href => "http://www.thetartan.org"} By The Tartan

      = yield(:above)

      #content
      
        #main
        
          - if notice
            %p.notice= notice
          - if alert
            %p.alert= alert
        
          #subnav
            = yield(:subnav)
        
          = yield
        
        #aside
          = link_to "Add an event", new_event_path, :class => 'add-event'
          %h4.section-header Search for an event
          = form_tag events_path, :method => :get, :class => "search-field" do
            = text_field_tag :query, "", {:type=>"search", :placeholder => "Search", :class => "search"}
            = submit_tag "Search"
          .ad= image_tag("ad.gif", :width => 160, :height => 600)
      #footer &copy; 2010 The Fence